Repository Manta-Network/manta-signer, pull requests merged in 2022-08, with the labels that each got.

#167 downgrade manta-rs
  .github/workflows/ci.yml
  Cargo.toml
  src/service.rs
Labels: L-skip

#164 Adding some communication between UI and backend to ensure sync at connection start
  CHANGELOG.md
  ui/src-tauri/rust-toolchain
  ui/src-tauri/src/main.rs
  ui/src/App.js
Labels: C-bug, L-fixed, A-ui

#166 Stop close button[X] on Authorization prompt from closing manta-signer
  CHANGELOG.md
  ui/src-tauri/src/main.rs
  ui/src/pages/Authorize.js
Labels: C-bug, L-fixed, A-tauri
