Repository Manta-Network/manta-signer, pull requests merged in 2022-06, with the labels that each got.

#103 Change release workflow
  .github/release.yaml
  .github/workflows/create_release.yaml
  .github/workflows/tag.yaml
Labels: norelease, changelog:changed

#85 feat: add Rust CI [#none]
  .github/workflows/ci.yml
Labels: changelog:added

#116 Upgrade tauri, add some messages
  .github/workflows/create_release.yaml
  .github/workflows/release.yml
  Cargo.toml
  ui/package.json
  ui/public/about.html
  ui/src-tauri/Cargo.lock
  ui/src-tauri/Cargo.toml
  ui/src-tauri/tauri.conf.json
  ui/src/pages/CreateAccount.js
  ui/src/pages/SignIn.js
  www/src/App.tsx
Labels: release:patch, changelog:skip

#119 feat: update parameter path from SDK to manta-parameters
  Cargo.toml
  src/log.rs
  src/parameters.rs
  src/service.rs
Labels: norelease, changelog:added
