Repository Manta-Network/manta-signer, pull requests merged in 2022-10, with the labels that each got.

#180 feat: add multiple origin URLs for CORS
  CHANGELOG.md
  src/config.rs
  src/service.rs
Labels: L-added

#182 Release v0.8.0
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  ui/package.json
  ui/public/about.html
  ui/src-tauri/Cargo.toml
  ui/src-tauri/tauri.conf.json
  www/src/App.tsx
Labels: release:minor, L-skip

#190 Update readme for building Manta Signer
  README.md
Labels: C-enhancement, L-added, A-documentation
