Repository Manta-Network/manta-signer, pull requests merged in 2023-03, with the labels that each got.

#329 Fix reimport / password reset
  .github/workflows/release.yml
  CHANGELOG.md
  ui/src-tauri/src/main.rs
Labels: L-fixed

#332 Add sinks validation
  .github/workflows/release.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/service.rs
Labels: C-enhancement, L-changed, A-compatibility

#338 change start to continue after signer ready
  CHANGELOG.md
  ui/src/App.js
  ui/src/pages/SignIn/SignIn.js
  ui/src/pages/SignIn/SignInSuccess.js
Labels: L-changed, A-ui

#343 Migrate storage
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/service.rs
Labels: C-enhancement, L-changed, A-compatibility

#339 Release 1.1.2
  CHANGELOG.md
  Cargo.toml
  ui/package.json
  ui/public/about.html
  ui/src-tauri/Cargo.toml
  ui/src-tauri/tauri.conf.json
  www/src/App.tsx
Labels: release:minor, L-skip

#344 Release v1.2.0
  CHANGELOG.md
  Cargo.lock
  ui/package.json
  ui/public/about.html
  ui/src-tauri/Cargo.toml
  ui/src-tauri/tauri.conf.json
  www/src/App.tsx
Labels: release:minor, L-skip

#348 Remove "soon" next to calamari for Calamari release
  CHANGELOG.md
  ui/src/pages/SignIn/SignInSuccess.js
Labels: L-changed

#349 Release v1.2.1
  CHANGELOG.md
  Cargo.toml
  ui/package.json
  ui/public/about.html
  ui/src-tauri/Cargo.toml
  ui/src-tauri/tauri.conf.json
  www/src/App.tsx
Labels: release:patch, L-skip
